### ISSUE TITLE
Missing/incorrect info: a03 Modules Link Unavailable

### ISSUE THREAD

**Issue by jadekeegan** [comp426-2023-spring/assignments#4]
#### URL of file with the missing/incorrect info
https://github.com/comp426-2023-spring/assignments#list-of-assignments

#### Line number with missing or incorrect info
Line 18 
https://github.com/comp426-2023-spring/assignments/blob/aa96135342cf94abb7420e41787abaf750b7d615/README.md?plain=1#L18

#### What is wrong?
The assignment link for a03: Modules has not been posted yet, but the suggested due date is 2/16.

#### What should be there instead?
The Github invite link for a03: modules.

**Comment by jdmar3** [comment]
Fixed in https://github.com/comp426-2023-spring/assignments/commit/75cce65e6bbd14087b7cbd5f90ff46c998857754. 

Due date updated to 2023-02-23.
